language: node_js
sudo: false
node_js:
  - 10
cache: yarn
after_success:
- npm install -g vsce
- vsce package
install: npm install
deploy:
  provider: script
  script: vsce publish -p $VS_TOKEN
  skip_cleanup: true
  on:
    tags: true
    repo: JulienCroain/markdown-viewer
    branch: master