splash = false

preload = ~/.config/hypr/wallpapers/38580.jpg

wallpaper {
	monitor = DP-2
	path = ~/.config/hypr/wallpapers/38580.jpg
	fit_mode = cover
}

wallpaper {
	monitor = DP-3
	path = ~/.config/hypr/wallpapers/38580.jpg
	fit_mode = cover
}

wallpaper {
	monitor =
	path = ~/.config/hypr/wallpapers/38580.jpg
	fit_mode = cover
}
