color0 #43474e
color1 #ffb4ab
color2 #a3c9fe
color3 #bcc7db
color4 #d8bde3
color5 #a3c9fe
color6 #bcc7db
color7 #e1e2e8
color8 #8d9199
color9 #ffb4ab
color10 #a3c9fe
color11 #bcc7db
color12 #d8bde3
color13 #a3c9fe
color14 #bcc7db
color15 #e1e2e8

cursor                #e1e2e8
cursor_text_color     #111418
background            #111418
foreground            #e1e2e8
selection_foreground  #c3c6cf
selection_background  #43474e
active_border_color   #a3c9fe
inactive_border_color #43474e
url_color             #a3c9fe

active_tab_foreground   #00315b
active_tab_background   #a3c9fe
inactive_tab_foreground #c3c6cf
inactive_tab_background #43474e
cursor_trail_color      #c3c6cf
