add_newline = true

format = "$username$hostname$directory$git_branch$git_status$python$nodejs$rust$golang$cmd_duration$line_break$character"

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"

[directory]
truncation_length = 4
truncate_to_repo = false
style = "bold cyan"

[git_branch]
symbol = "git:"
style = "bold yellow"

[git_status]
style = "bold red"

[cmd_duration]
min_time = 1000
format = "took [$duration](bold blue) "

[hostname]
ssh_only = false
format = "[@$hostname](bold dimmed white) "

[username]
show_always = true
format = "[$user](bold white)"
