# Environment
env = XCURSOR_SIZE,24
env = SIGNAL_PASSWORD_STORE,kwallet6
env = CHROME_PASSWORD_STORE,kwallet6
env = XDG_DATA_DIRS,/usr/local/share:/usr/share:$HOME/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:$HOME/.local/share
