# Environment
env = PATH,$HOME/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/bin:/usr/lib/llvm/21/bin:/bin:/usr/sbin:/sbin
env = XCURSOR_SIZE,24
env = SIGNAL_PASSWORD_STORE,kwallet6
env = CHROME_PASSWORD_STORE,kwallet6
env = XDG_DATA_DIRS,/usr/local/share:/usr/share:$HOME/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:$HOME/.local/share
