# Window rules
windowrule = match:class ^(Steam)$, float on
windowrule = match:class ^(discord|Discord)$, float on

# Steam games (class: steam_app_<appid>) always open on DP-3
windowrule = monitor DP-3, match:class ^(steam_app_\d+)$
