# General window behavior
general {
    gaps_in = 8
    gaps_out = 14
    border_size = 3
    col.active_border = rgba(7aa2f7ee) rgba(f7768eee) 45deg
    col.inactive_border = rgba(414868cc)
    layout = dwindle
}
