# Aliases
alias ls='exa --color=auto'
alias grep='grep --color=auto'
alias ll='exa -lah --color=auto --group-directories-first'
alias la='exa -A --color=auto'
alias l='exa -1 --color=auto'
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gco='git checkout'
alias gl='git log'
alias npmstart='npm start'
alias npminstall='npm install'
alias dps='docker ps'
alias di='docker images'
alias drm='docker rm'
alias drmi='docker rmi'
alias ..='cd ..'
alias ...='cd ../..'
alias cat='bat --paging=always'
